name: JederSMS
description: An SMS Plugin
version: 1.0
author: Ostrichbeta Chan
commands:
  jederSMS:
    aliases: [sms]
    description: jederSMS Main Command
    usage: /jederSMS <send|receive|help|version|info> {...}

permissions:
  jederSMS.*:
    description: The highest permission of the plugin
    children:
      jederSMS.send: true
      jederSMS.receive: true
      jederSMS.msglist: true
      jederSMS.delete: true
      jederSMS.superDelete: true

  jederSMS.send:
    description: The permission to send the message
    default: true

  jederSMS.receive:
    description: The permission to receive the message
    default: true

  jederSMS.msglist:
    description: The permission to show the list of message
    default: false

  jederSMS.delete:
    description: The permission to delete the message
    default: true

  jederSMS.superDelete:
    description: The permission to delete all the message
    default: op